<?php
/**
 * llms.txt generator — generates the AI sitemap document.
 *
 * Caches output locally for 5 minutes (transient).
 * Falls back to backend-served content when available.
 *
 * Reference: https://llmstxt.org
 *
 * @package Quoted
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class Quoted_Llms_Txt {

	const CACHE_KEY = 'quoted_llms_txt_v1';
	const CACHE_TTL = 300; // 5 minutes

	/**
	 * Get the llms.txt content for this site.
	 *
	 * Strategy:
	 *  1. Check local transient cache.
	 *  2. Try backend (single source of truth).
	 *  3. Fall back to locally-generated version.
	 *
	 * @return string
	 */
	public function get_content() {
		$cached = get_transient( self::CACHE_KEY );
		if ( $cached !== false ) {
			return $cached;
		}

		$content = $this->fetch_from_backend();
		if ( $content === null ) {
			$content = $this->generate_locally();
		}

		set_transient( self::CACHE_KEY, $content, self::CACHE_TTL );
		return $content;
	}

	/**
	 * Try to fetch from backend.
	 *
	 * @return string|null
	 */
	private function fetch_from_backend() {
		$license = new Quoted_License();
		if ( ! $license->is_connected() ) {
			return null;
		}

		$api = new Quoted_Api_Client();
		$result = $api->get_public( '/api/public/llm/sitemap.txt' );

		if ( is_wp_error( $result ) ) {
			return null;
		}

		if ( is_string( $result ) && strlen( $result ) > 0 ) {
			return $result;
		}

		return null;
	}

	/**
	 * Locally-generated llms.txt as fallback.
	 * Lists up to 50 most recent posts/pages.
	 */
	private function generate_locally() {
		$site_name = get_bloginfo( 'name' );
		$site_desc = get_bloginfo( 'description' );
		$home_url  = home_url();

		$out  = "# " . $this->safe_md( $site_name ) . "\n\n";
		if ( ! empty( $site_desc ) ) {
			$out .= "> " . $this->safe_md( $site_desc ) . "\n\n";
		}
		$out .= "Site URL: " . $home_url . "\n\n";

		$posts = get_posts( array(
			'numberposts' => 50,
			'post_type'   => array( 'post', 'page' ),
			'post_status' => 'publish',
			'orderby'     => 'modified',
			'order'       => 'DESC',
		) );

		if ( ! empty( $posts ) ) {
			$out .= "## Content\n\n";
			foreach ( $posts as $post ) {
				$title = $this->safe_md( $post->post_title );
				$md_url = $this->markdown_url_for_post( $post );
				$excerpt = $this->safe_md( wp_trim_words( wp_strip_all_tags( $post->post_content ), 25, '...' ) );
				$out .= "- [{$title}]({$md_url}): {$excerpt}\n";
			}
			$out .= "\n";
		}

		$out .= "## About\n\n";
		$out .= "This is the AI-readable sitemap for {$site_name}. ";
		$out .= "Each linked URL returns clean markdown for AI processing.\n\n";
		$out .= "Generated by Quoted (https://quoted.io) on " . gmdate( 'Y-m-d' ) . ".\n";

		return $out;
	}

	private function markdown_url_for_post( $post ) {
		return home_url( '/wp-json/quoted/v1/llm/' . sanitize_title( $post->post_name ) );
	}

	/**
	 * Strip characters that would break markdown structure.
	 */
	private function safe_md( $str ) {
		$str = wp_strip_all_tags( $str );
		$str = preg_replace( '/[\r\n]+/', ' ', $str );
		$str = trim( $str );
		// Escape brackets that would form unintended links.
		$str = str_replace( array( '[', ']' ), array( '\[', '\]' ), $str );
		return $str;
	}

	/**
	 * Manual cache invalidation hook (e.g., on post save).
	 */
	public static function flush_cache() {
		delete_transient( self::CACHE_KEY );
	}
}
