<?php
/**
 * llms.txt generator — generates the AI sitemap document.
 *
 * Caches output locally for 5 minutes (transient). Local-first; no external
 * service is contacted.
 *
 * Reference: https://llmstxt.org
 *
 * @package Quoted
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class Quoted_Llms_Txt {

	const CACHE_KEY = 'quoted_llms_txt_v1';
	const CACHE_TTL = 300; // 5 minutes

	/**
	 * Default per-request post count. A very large WordPress site (10k+ posts)
	 * generating a single llms.txt every request would be expensive, so we
	 * default to 1000 most-recent posts. Operators with bigger sites can
	 * override via the `quoted_llms_txt_post_limit` filter or pass -1 to
	 * include every published post.
	 *
	 * @since 0.5.0
	 */
	const DEFAULT_POST_LIMIT = 1000;

	/**
	 * Get the llms.txt content for this site.
	 *
	 * Reads from a 5-minute transient cache, generates locally on miss.
	 *
	 * @return string
	 */
	public function get_content() {
		$cached = get_transient( self::CACHE_KEY );
		if ( $cached !== false ) {
			return $cached;
		}

		$content = $this->generate_locally();

		set_transient( self::CACHE_KEY, $content, self::CACHE_TTL );
		return $content;
	}

	/**
	 * Generate llms.txt from this site's posts and pages.
	 *
	 * The number of items is filterable; pass -1 to include every published
	 * post. Default 1000 is a performance ceiling, not a feature gate.
	 */
	private function generate_locally() {
		$site_name = get_bloginfo( 'name' );
		$site_desc = get_bloginfo( 'description' );
		$home_url  = home_url();

		$out  = "# " . $this->safe_md( $site_name ) . "\n\n";
		if ( ! empty( $site_desc ) ) {
			$out .= "> " . $this->safe_md( $site_desc ) . "\n\n";
		}
		$out .= "Site URL: " . $home_url . "\n\n";

		/**
		 * Filter the max number of posts/pages included in llms.txt.
		 *
		 * Default is 1000 to keep the file generation fast on large sites.
		 * Pass -1 to include every published post regardless of count.
		 *
		 * @param int $limit Max number of items (-1 for unlimited).
		 */
		$limit = apply_filters( 'quoted_llms_txt_post_limit', self::DEFAULT_POST_LIMIT );
		$limit = is_numeric( $limit ) ? (int) $limit : self::DEFAULT_POST_LIMIT;

		$posts = get_posts( array(
			'numberposts' => $limit,
			'post_type'   => array( 'post', 'page' ),
			'post_status' => 'publish',
			'orderby'     => 'modified',
			'order'       => 'DESC',
		) );

		if ( ! empty( $posts ) ) {
			$out .= "## Content\n\n";
			foreach ( $posts as $post ) {
				$title = $this->safe_md( $post->post_title );
				$md_url = $this->markdown_url_for_post( $post );
				$excerpt = $this->safe_md( wp_trim_words( wp_strip_all_tags( $post->post_content ), 25, '...' ) );
				$out .= "- [{$title}]({$md_url}): {$excerpt}\n";
			}
			$out .= "\n";
		}

		$out .= "## About\n\n";
		$out .= "This is the AI-readable sitemap for {$site_name}. ";
		$out .= "Each linked URL returns clean markdown for AI processing.\n\n";
		$out .= "Generated by Quoted on " . gmdate( 'Y-m-d' ) . ".\n";

		return $out;
	}

	private function markdown_url_for_post( $post ) {
		// Use rest_url() instead of home_url('/wp-json/...') — REST prefix can be
		// remapped via the `rest_url_prefix` filter or have a different base
		// when the API is mounted somewhere other than /wp-json/.
		return rest_url( 'quoted/v1/llm/' . sanitize_title( $post->post_name ) );
	}

	/**
	 * Strip characters that would break markdown structure.
	 */
	private function safe_md( $str ) {
		$str = wp_strip_all_tags( $str );
		$str = preg_replace( '/[\r\n]+/', ' ', $str );
		$str = trim( $str );
		// Escape brackets that would form unintended links.
		$str = str_replace( array( '[', ']' ), array( '\[', '\]' ), $str );
		return $str;
	}

	/**
	 * Manual cache invalidation hook (e.g., on post save).
	 */
	public static function flush_cache() {
		delete_transient( self::CACHE_KEY );
	}
}
