<?php
/**
 * llms.txt generator — generates the AI sitemap document.
 *
 * Caches output locally for 5 minutes (transient).
 * Honors options: content type filter (posts/pages/products), site summary,
 * excluded URL list, plan-based post cap.
 *
 * Reference: https://llmstxt.org
 *
 * @package Quoted
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class Quoted_Llms_Txt {

	const CACHE_KEY = 'quoted_llms_txt_v1';
	const CACHE_TTL = 300; // 5 minutes

	/**
	 * Return the llms.txt content for this site (cached).
	 *
	 * @return string
	 */
	public function get_content() {
		// Honor the master enable toggle — when off, serve a tiny note so
		// the route still returns 200 (rather than 404).
		if ( ! get_option( 'quoted_llmstxt_enabled', true ) ) {
			return "# " . $this->safe_md( get_bloginfo( 'name' ) ) . "\n\n> llms.txt generation is disabled.\n";
		}

		$cached = get_transient( self::CACHE_KEY );
		if ( $cached !== false ) {
			return $cached;
		}

		$content = $this->generate_locally();
		set_transient( self::CACHE_KEY, $content, self::CACHE_TTL );
		return $content;
	}

	/**
	 * Effective post cap from the current plan.
	 * Returns 0 to mean unlimited.
	 */
	public static function effective_cap() {
		$plan = class_exists( 'Quoted_License' ) ? Quoted_License::current_plan() : 'free';
		return ( $plan === 'free' ) ? 50 : 0;
	}

	/**
	 * Locally-generated llms.txt.
	 */
	private function generate_locally() {
		$site_name = get_bloginfo( 'name' );
		$summary   = trim( (string) get_option( 'quoted_llmstxt_summary', '' ) );
		if ( $summary === '' ) {
			$summary = (string) get_bloginfo( 'description' );
		}
		$home_url = home_url();

		$inc_posts    = (bool) get_option( 'quoted_llmstxt_include_posts', true );
		$inc_pages    = (bool) get_option( 'quoted_llmstxt_include_pages', true );
		$inc_products = (bool) get_option( 'quoted_llmstxt_include_products', false );
		$excluded     = (array) get_option( 'quoted_llmstxt_excluded', array() );
		$cap          = self::effective_cap();

		$out  = "# " . $this->safe_md( $site_name ) . "\n\n";
		if ( ! empty( $summary ) ) {
			$out .= "> " . $this->safe_md( $summary ) . "\n\n";
		}
		$out .= "Site URL: " . $home_url . "\n\n";

		// Posts
		if ( $inc_posts ) {
			$posts = $this->fetch( array( 'post' ), $cap );
			$posts = $this->apply_excludes( $posts, $excluded );
			if ( ! empty( $posts ) ) {
				$out .= "## Posts\n\n" . $this->render_list( $posts );
			}
		}

		// Pages
		if ( $inc_pages ) {
			$pages = $this->fetch( array( 'page' ), $cap > 0 ? $cap : -1 );
			$pages = $this->apply_excludes( $pages, $excluded );
			if ( ! empty( $pages ) ) {
				$out .= "## Pages\n\n" . $this->render_list( $pages );
			}
		}

		// WooCommerce products (Pro tier — only emit if Woo active and toggle on).
		if ( $inc_products && post_type_exists( 'product' ) ) {
			$products = $this->fetch( array( 'product' ), $cap > 0 ? $cap : -1 );
			$products = $this->apply_excludes( $products, $excluded );
			if ( ! empty( $products ) ) {
				$out .= "## Products\n\n" . $this->render_list( $products );
			}
		}

		$out .= "## About\n\n";
		$out .= "This is the AI-readable sitemap for {$site_name}. ";
		$out .= "Each linked URL returns clean markdown for AI processing.\n\n";
		$out .= "Generated by Quoted (https://quotedeasy.com) on " . gmdate( 'Y-m-d' ) . ".\n";

		return $out;
	}

	private function fetch( $types, $cap ) {
		$args = array(
			'numberposts' => $cap > 0 ? $cap : -1,
			'post_type'   => $types,
			'post_status' => 'publish',
			'orderby'     => 'modified',
			'order'       => 'DESC',
		);
		return get_posts( $args );
	}

	private function apply_excludes( $posts, $excluded ) {
		if ( empty( $excluded ) ) {
			return $posts;
		}
		$out = array();
		foreach ( $posts as $post ) {
			$path = wp_parse_url( get_permalink( $post ), PHP_URL_PATH );
			$slug = $post->post_name;
			$skip = false;
			foreach ( $excluded as $needle ) {
				$needle = trim( (string) $needle );
				if ( $needle === '' ) {
					continue;
				}
				if ( $needle === $path || $needle === $slug || strpos( (string) $path, $needle ) !== false ) {
					$skip = true;
					break;
				}
			}
			if ( ! $skip ) {
				$out[] = $post;
			}
		}
		return $out;
	}

	private function render_list( $posts ) {
		$out = '';
		foreach ( $posts as $post ) {
			$title   = $this->safe_md( $post->post_title );
			$md_url  = $this->markdown_url_for_post( $post );
			$excerpt = $this->safe_md( wp_trim_words( wp_strip_all_tags( $post->post_content ), 25, '...' ) );
			$out    .= "- [{$title}]({$md_url}): {$excerpt}\n";
		}
		return $out . "\n";
	}

	private function markdown_url_for_post( $post ) {
		return home_url( '/wp-json/quoted/v1/llm/' . sanitize_title( $post->post_name ) );
	}

	/**
	 * Strip characters that would break markdown structure.
	 */
	private function safe_md( $str ) {
		$str = wp_strip_all_tags( $str );
		$str = preg_replace( '/[\r\n]+/', ' ', $str );
		$str = trim( $str );
		$str = str_replace( array( '[', ']' ), array( '\[', '\]' ), $str );
		return $str;
	}

	/**
	 * Manual cache invalidation hook (e.g., on post save).
	 */
	public static function flush_cache() {
		delete_transient( self::CACHE_KEY );
	}
}
